/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.begoingto.app;

import com.begoingto.app.internal.HomeScreen;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import raven.modal.ModalDialog;
import raven.modal.component.SimpleModalBorder;
import raven.modal.option.Option;

/**
 *
 * @author begoingto
 */
public class MainApp extends javax.swing.JFrame {

    private Boolean isDarkTheme = true;

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.startHomeScreen();
        this.modalDebug();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mModal = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mHome = new javax.swing.JMenu();
        mCategory = new javax.swing.JMenu();
        mProduct = new javax.swing.JMenu();
        mTable = new javax.swing.JMenu();
        mStaff = new javax.swing.JMenu();
        mPOS = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mReport = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        mTheme = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1097, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save As");
        jMenu1.add(jMenuItem2);

        mModal.setText("Modal");
        mModal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mModalMouseClicked(evt);
            }
        });
        mModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModalActionPerformed(evt);
            }
        });
        jMenu1.add(mModal);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        mHome.setText("Home");
        mHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHomeMouseClicked(evt);
            }
        });
        mHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(mHome);

        mCategory.setText("Category");
        jMenuBar1.add(mCategory);

        mProduct.setText("Product");
        jMenuBar1.add(mProduct);

        mTable.setText("Table");
        jMenuBar1.add(mTable);

        mStaff.setText("Staff");
        jMenuBar1.add(mStaff);

        mPOS.setText("POS");
        jMenuBar1.add(mPOS);

        jMenu2.setText("Kitchen");
        jMenuBar1.add(jMenu2);

        mReport.setText("Report");
        jMenuBar1.add(mReport);

        jMenu3.setText("Setting");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Booking");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Purchasing");
        jMenuBar1.add(jMenu5);

        mTheme.setText("Theme");
        mTheme.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mThemeMenuSelected(evt);
            }
        });
        mTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mThemeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mTheme);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mThemeMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mThemeMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_mThemeMenuSelected

    private void mThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mThemeMouseClicked
        // TODO add your handling code here:
        isDarkTheme = !isDarkTheme;
        System.out.println("Theme mThemeMouseClicked: " + isDarkTheme);
        if (isDarkTheme) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatMacDarkLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatMacLightLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_mThemeMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mHomeActionPerformed

    private void mHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHomeMouseClicked
        // TODO add your handling code here:
        this.startHomeScreen();

    }//GEN-LAST:event_mHomeMouseClicked

    private void mModalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mModalMouseClicked
        // TODO add your handling code here:
        this.modalDebug();
    }//GEN-LAST:event_mModalMouseClicked

    private void mModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModalActionPerformed
        // TODO add your handling code here:
        this.modalDebug();
    }//GEN-LAST:event_mModalActionPerformed

    private void modalDebug() {
        SimpleModalBorder m = new SimpleModalBorder(rootPane, "Login");
        m.setVisible(true);
        JTextArea txt = new JTextArea();
        txt.setEditable(false);
        txt.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:5,35,5,35");
        txt.setText("Sets the default hide mode for the layout. This hide mode can be overridden by the component constraint."
                + "\nThe hide mode specified how the layout manager should handle a component that isn't visible.");
        ModalDialog.showModal(this, new SimpleModalBorder(txt, "Sample Message", SimpleModalBorder.YES_NO_OPTION, null), this.getModalOption());
    }

    private Option getModalOption() {
        Option option = ModalDialog.createOption();
        option.setCloseOnPressedEscape(false);
        option.setBackgroundClickType(Option.BackgroundClickType.BLOCK);
        return option;
    }

    private void startHomeScreen() {
        HomeScreen frm = new HomeScreen();
        try {
            frm.setMaximum(true);
            frm.setClosable(true);
            frm.setMaximizable(true);
            frm.setIconifiable(true);
            frm.setResizable(true);
            this.jDesktop.add(frm).setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
            UIManager.put("Button.arc", 8);
            UIManager.put("Component.arc", 8);
            UIManager.put("ProgressBar.arc", 8);
            UIManager.put("TextComponent.arc", 8);
        } catch (UnsupportedLookAndFeelException e) {
//            throw new IllegalAccessError(e.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mCategory;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenuItem mModal;
    private javax.swing.JMenu mPOS;
    private javax.swing.JMenu mProduct;
    private javax.swing.JMenu mReport;
    private javax.swing.JMenu mStaff;
    private javax.swing.JMenu mTable;
    private javax.swing.JMenu mTheme;
    // End of variables declaration//GEN-END:variables
}
